env:
  contexts:
    - name: "Link-ZAP-Scanner"
      urls:
        - "https://your-target-app.com"
      includePaths:
        - "https://your-target-app.com/.*"
      excludePaths:
        - "https://your-target-app.com/logout.*"
        - "https://your-target-app.com/api/auth/signout.*"
        - ".*\.pdf"
        - ".*\.zip"
      
      # --- Authentication Section ---
      authentication:
        method: "form"
        parameters:
          loginPageUrl: "https://your-target-app.com/login"
          loginRequestUrl: "https://your-target-app.com/api/login"
          loginRequestBody: "username={%username%}&password={%password%}"
        verification:
          method: "response"
          loggedOutRegex: 'href="/login"' # Tells ZAP "If you see this, you are logged out"
          pollFrequency: 60
      
      sessionManagement:
        method: "cookie"
        parameters: {}
      
      users:
        - name: "test-user"
          credentials:
            username: "admin@example.com"
            password: "verysecurepassword123"

  parameters:
    failOnError: true
    failOnWarning: false
    continueOnFailure: false

jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
      scanOnlyInScope: true

  - type: spider
    parameters:
      context: "Link-ZAP-Scanner"
      user: "test-user" # Tells the spider to crawl as the authenticated user
      maxDuration: 5

  - type: ajaxSpider
    parameters:
      context: "Link-ZAP-Scanner"
      user: "test-user"
      browserId: "firefox-headless"
      maxDuration: 10
      maxCrawlDepth: 10
      numberOfBrowsers: 2

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: "Link-ZAP-Scanner"
      user: "test-user" # Attacks the app using the authenticated session
      policy: "Default Policy"
      maxRuleDurationInMins: 2
      maxScanDurationInMins: 60
      addQueryParam: true

  - type: report
    parameters:
      template: "modern-red-confidential"
      reportDir: "/zap/wrk/reports"
      reportFile: "work-app-security-report"
